### ISSUE TITLE
Replace get_storage_var_address

### ISSUE THREAD

**Issue by marioiordanov** [0xSpaceShard/starknet-devnet-rs#221]
Replace `get_storage_var_address` function implementation with starknet_rs.
https://github.com/0xSpaceShard/starknet-devnet-rs/blob/bb22e929e6e6e666b9be4a5ce549933e08fd2ce7/crates/starknet/src/utils.rs#L18

**Comment by ATREAY** [comment]
hey @marioiordanov, can I work on this issue if you are not already working on it?

**Comment by devnet0x** [comment]
Hi, @ivpavici @marioiordanov , i would love to be assigned to this good first issue if it's not already assigned.

**Comment by marioiordanov** [comment]
You can do it

**Comment by devnet0x** [comment]
gn...please your review...:bowtie:

**Comment by devnet0x** [comment]
Hi, i think i made a mistake...this issue must remove use crate::utils::get_storage_var_address and replace with starknet_rs_core::utils::get_storage_var_address in all other files?

**Comment by devnet0x** [comment]
Hi, please your help, i think i'm not understanding. Function get_storage_var_address implementation is already using starknet_rs_core which is starknet_rs. I'm not understanding what i have to do.

pub(crate) fn get_storage_var_address(
    storage_var_name: &str,
    args: &[Felt],
) -> DevnetResult<StorageKey> {
    let storage_var_address = starknet_rs_core::utils::get_storage_var_address(

**Comment by ivpavici** [comment]
> pub(crate) fn get_storage_var_address( storage_var_name: &str, args: &[Felt], ) -> DevnetResult { let storage_var_address = starknet_rs_core::utils::get_storage_var_address(

where is this code from? The description of the task is pretty clear I think , but we don't know what you have in mind without a PR!

**Comment by devnet0x** [comment]
Hi, this code is from 0xSpaceShard/starknet-devnet-rs spaceshard github. As you can see get_storage_var_address implementation is already using starknet-rs. So i don't understand what i have to do, please if you could give me some advice, maybe i'm missing something?:

![image](https://github.com/0xSpaceShard/starknet-devnet-rs/assets/117481421/0c3043d3-ba80-406e-8055-2261a7a16934)

**Comment by ivpavici** [comment]
@devnet0x sorry, I must have looked at the old branch.
Anyway, we clarified, and it would probably be a good idea to actually replace every occurrence of `get_storage_var_address` in the devnet with the `starknet-rs` one...

Soes that sound ok?

**Comment by devnet0x** [comment]
Ok, i will work on that, thanks.

**Comment by devnet0x** [comment]
Hi @ivpavici , please check this PR...thanks

**Comment by RajeshRk18** [comment]
Can I work on this?

**Comment by devnet0x** [comment]
Hi @RajeshRk18 yes please. Sorry guys i don't know how to handle this issue.

**Comment by RajeshRk18** [comment]
@ivpavici Can you add this to ODhack? :)

**Comment by FabijanC** [comment]
Hey @RajeshRk18,

As discussed with @marioiordanov, it turns out that this issue was resolved in #332. That PR introduced the use of the starknet-rs implementation of `get_storage_var_addres` inside of our utility function of the same name. We did not realize this because this issue's description contains a permalink to an old revision of the code where this is not the case. Completely replacing our utility function with the starknet-rs one would be too cumbersome due to all the necessary `Result` mapping.

We are sorry that you spent several working days on this, but since you helped us discover that this issue is resolved and closeable, you can expect a refund. The same applies to @devnet0x.

Cheers!

**Comment by FabijanC** [comment]
money

**Comment by RajeshRk18** [comment]
> money

Even though I am not resolving this issue(since it's already been done), I will still get some money?

**Comment by FabijanC** [comment]
> Even though I am not resolving this issue(since it's already been done), I will still get some money?

That's what I've been told. It would not be a precedent as it's happened before: https://github.com/0xSpaceShard/starknet-devnet-rs/issues/111#issuecomment-2074901794

However, if receiving refund would in this case constitute a violation against your moral principles, feel free to say state so, and none shall be sent to you.

**Comment by RajeshRk18** [comment]
> > Even though I am not resolving this issue(since it's already been done), I will still get some money?
> 
> That's what I've been told. It would not be a precedent as it's happened before: https://github.com/0xSpaceShard/starknet-devnet-rs/issues/111#issuecomment-2074901794
> 
> However, if receiving refund would in this case constitute a violation against your moral principles, feel free to say state so, and none shall be sent to you.

Great if I get some as I spent time on it

**Comment by ivpavici** [comment]
yes, @RajeshRk18 and @devnet0x I will send you a reward on OnlyDust
